### ISSUE TITLE
Set Fan speed?

### ISSUE THREAD

**Issue by SaulGoodman1337** [ThomasWilla/PSHardwareMonitoring#2]
Hello, Thomas, 
i have currently built something similar for my home project and found your project while searching for information.

Do you have any idea how I can set values ?
e.g. case fan.
I would be very grateful for your help.

**Comment by ThomasWilla** [comment]
Hi Saul Goodman :-)

sorry for my late answer. I don't saw this issue.

Maybe you can control the fan with the CIM Class Win32_Fan. There is a method setspeed

Get-CimClass -ClassName Win32_Fan | select CimClassMethods
Unfortunately i can't test it, because i don't have fans anymore :-)
